#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include "rkllm.h"

// Forward declaration of Go callback (generated by cgo via //export goCallback).
// We declare it here so wrapper can call it.
extern int goCallback(RKLLMResult* result, void* userdata, LLMCallState state);

// Implementations placed in this single C file to avoid multiple definition issues.
int c_callback(RKLLMResult* result, void* userdata, LLMCallState state) {
    return goCallback(result, userdata, state);
}

int set_rkllm_input_prompt(RKLLMInput* in, const char* role, const char* prompt) {
    in->role = role;
    in->input_type = RKLLM_INPUT_PROMPT;
    in->prompt_input = prompt;
    return 0;
}
